# Generated by Django 5.2.5 on 2025-08-08 10:34

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.utils.profile_picture_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('photographer', 'Photographer'), ('client', 'Client')], max_length=20),
        ),
    ]
