# Generated by Django 5.2.5 on 2025-08-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_picture_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographerprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('photographer', 'Photographer'), ('client', 'Client')], default='client', max_length=20),
        ),
        migrations.DeleteModel(
            name='ClientProfile',
        ),
        migrations.DeleteModel(
            name='PhotographerProfile',
        ),
    ]
