# Generated by Django 5.2.5 on 2025-08-25 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('photographers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpreference',
            name='photographer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_preference', to='photographers.photographer'),
        ),
    ]
