# Generated by Django 5.2.5 on 2025-08-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepackage',
            old_name='duration_minutes',
            new_name='duration',
        ),
    ]
