# Generated by Django 5.2.5 on 2025-08-15 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_duration_minutes_servicepackage_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_days', models.JSONField(default=list, help_text="List of days available for booking, e.g., ['Monday', 'Tuesday']")),
                ('start_time', models.TimeField(blank=True, help_text='Earliest time available for bookings', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Latest time available for bookings', null=True)),
                ('min_notice_hours', models.PositiveIntegerField(default=24, help_text='Minimum notice required before booking (in hours)')),
                ('max_future_days', models.PositiveIntegerField(default=180, help_text='How many days in advance clients can book')),
                ('allow_same_day', models.BooleanField(default=False)),
                ('deposit_required', models.BooleanField(default=False)),
                ('deposit_percentage', models.PositiveIntegerField(default=0, help_text='Deposit percentage if required')),
                ('auto_confirm', models.BooleanField(default=False, help_text='If true, bookings are auto-confirmed without manual approval')),
                ('notes', models.TextField(blank=True, help_text='Additional booking instructions for clients')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photographer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Preference',
                'verbose_name_plural': 'Booking Preferences',
            },
        ),
    ]
