# Generated by Django 5.2.5 on 2025-08-10 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public Gallery')], default='private', max_length=20)),
                ('is_shareable_via_link', models.BooleanField(default=False)),
                ('share_token', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessible_users', models.ManyToManyField(blank=True, related_name='accessible_galleries', to=settings.AUTH_USER_MODEL)),
                ('assigned_clients', models.ManyToManyField(blank=True, related_name='assigned_galleries', to=settings.AUTH_USER_MODEL)),
                ('parent_gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_galleries', to='gallery.gallery')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_photos/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public Photo')], default='private', max_length=20)),
                ('is_shareable_via_link', models.BooleanField(default=False)),
                ('share_token', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('accessible_users', models.ManyToManyField(blank=True, related_name='accessible_photos', to=settings.AUTH_USER_MODEL)),
                ('assigned_clients', models.ManyToManyField(blank=True, related_name='assigned_photos', to=settings.AUTH_USER_MODEL)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='PublicGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.BooleanField(default=False)),
                ('added_to_public_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_listing', to='gallery.gallery')),
            ],
            options={
                'verbose_name_plural': 'Public Galleries',
            },
        ),
        migrations.CreateModel(
            name='SharedAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_method', models.CharField(choices=[('share_link', 'Via Share Link'), ('public_gallery', 'From Public Gallery'), ('assigned', 'Directly Assigned')], max_length=20)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'gallery'), ('user', 'photo')},
            },
        ),
    ]
