# Generated by Django 5.2.5 on 2025-08-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='defaults',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='defaults',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='is_shareable_via_link',
            field=models.BooleanField(default=False, help_text='Allow sharing this gallery via a unique link'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public Gallery')], default='private', help_text='Controls who can discover and view this gallery', max_length=20),
        ),
        migrations.AlterField(
            model_name='photo',
            name='is_shareable_via_link',
            field=models.BooleanField(default=False, help_text='Allow sharing this photo via a unique link'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public Photo')], default='private', help_text='Controls who can discover and view this photo', max_length=20),
        ),
    ]
