# Generated by Django 5.2.5 on 2025-08-15 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_defaults_photo_defaults_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_public_view', models.BooleanField(default=True)),
                ('allow_downloads', models.BooleanField(default=False)),
                ('watermark_images', models.BooleanField(default=True)),
                ('watermark_text', models.CharField(blank=True, help_text='Text to use for watermarking images', max_length=255, null=True)),
                ('watermark_logo', models.ImageField(blank=True, help_text='Logo to use for watermarking images', null=True, upload_to='watermark_logos/')),
                ('items_per_page', models.PositiveIntegerField(default=20)),
                ('default_sort_order', models.CharField(choices=[('newest', 'Newest First'), ('oldest', 'Oldest First'), ('popular', 'Most Viewed')], default='newest', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
