# Generated by Django 5.2.5 on 2025-08-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_gallerypreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='selection_mode',
            field=models.BooleanField(default=False, help_text='Enable selection mode for clients to select photos'),
        ),
    ]
