# Generated by Django 5.2.5 on 2025-08-25 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('CNY', 'CNY'), ('INR', 'INR'), ('NGN', 'NGN'), ('GHS', 'GHS'), ('ZAR', 'ZAR'), ('KES', 'KES'), ('UGX', 'UGX'), ('TZS', 'TZS'), ('RWF', 'RWF'), ('BIF', 'BIF'), ('CDF', 'CDF'), ('XAF', 'XAF'), ('XOF', 'XOF'), ('XPF', 'XPF'), ('MAD', 'MAD'), ('DZD', 'DZD'), ('TND', 'TND'), ('LYD', 'LYD'), ('EGP', 'EGP'), ('SDG', 'SDG'), ('SSP', 'SSP'), ('ETB', 'ETB'), ('ERN', 'ERN'), ('MZN', 'MZN'), ('AOA', 'AOA'), ('ZMW', 'ZMW'), ('MWK', 'MWK'), ('LSL', 'LSL'), ('SZL', 'SZL'), ('MUR', 'MUR'), ('SCR', 'SCR'), ('MRU', 'MRU'), ('GNF', 'GNF'), ('SLL', 'SLL'), ('LRD', 'LRD'), ('BWP', 'BWP'), ('NAD', 'NAD'), ('MGA', 'MGA'), ('KMF', 'KMF'), ('STN', 'STN'), ('SOS', 'SOS')], default='USD', max_length=10)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('all_clients', models.ManyToManyField(related_name='photographers', through='photographers.Client', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photographer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_tags', to='photographers.photographer'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('photographer', 'user')},
        ),
    ]
