# Generated by Django 5.2.5 on 2025-08-12 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photographer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='photographers.photographer'),
            preserve_default=False,
        ),
    ]
