# Generated by Django 5.2.5 on 2025-08-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0003_client_photographer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='studio_name',
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='website',
        ),
    ]
