# Generated by Django 5.2.5 on 2025-08-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0004_remove_photographer_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='bio',
        ),
    ]
