# Generated by Django 5.2.5 on 2025-08-15 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0005_remove_photographer_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='profile_picture',
        ),
    ]
