# Generated by Django 5.2.5 on 2025-08-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0006_remove_photographer_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='year_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
