# Generated by Django 5.2.5 on 2025-08-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0007_photographer_year_of_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photographer',
            old_name='year_of_experience',
            new_name='years_of_experience',
        ),
    ]
