# Generated by Django 5.2.5 on 2025-08-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0008_rename_year_of_experience_photographer_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
    ]
