# Generated by Django 5.2.5 on 2025-08-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0009_photographer_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('CNY', 'CNY'), ('INR', 'INR'), ('NGN', 'NGN'), ('GHS', 'GHS'), ('ZAR', 'ZAR'), ('KES', 'KES'), ('UGX', 'UGX'), ('TZS', 'TZS'), ('RWF', 'RWF'), ('BIF', 'BIF'), ('CDF', 'CDF'), ('XAF', 'XAF'), ('XOF', 'XOF'), ('XPF', 'XPF'), ('MAD', 'MAD'), ('DZD', 'DZD'), ('TND', 'TND'), ('LYD', 'LYD'), ('EGP', 'EGP'), ('SDG', 'SDG'), ('SSP', 'SSP'), ('ETB', 'ETB'), ('ERN', 'ERN'), ('MZN', 'MZN'), ('AOA', 'AOA'), ('ZMW', 'ZMW'), ('MWK', 'MWK'), ('LSL', 'LSL'), ('SZL', 'SZL'), ('MUR', 'MUR'), ('SCR', 'SCR'), ('MRU', 'MRU'), ('GNF', 'GNF'), ('SLL', 'SLL'), ('LRD', 'LRD'), ('BWP', 'BWP'), ('NAD', 'NAD'), ('MGA', 'MGA'), ('KMF', 'KMF'), ('STN', 'STN'), ('SOS', 'SOS')], default='USD', max_length=10),
        ),
    ]
