# Generated by Django 5.2.5 on 2025-08-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='booking_reminders',
            field=models.BooleanField(default=True, help_text='Reminders for upcoming bookings'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='client_messages',
            field=models.BooleanField(default=True, help_text='Notifications for direct client messages'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive notifications via email'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='marketing_emails',
            field=models.BooleanField(default=False, help_text='Receive promotional and marketing emails'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='payment_alerts',
            field=models.BooleanField(default=True, help_text='Alerts for payments and transactions'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='push_notifications',
            field=models.BooleanField(default=True, help_text='Receive push notifications in app'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='quiet_end',
            field=models.TimeField(blank=True, help_text='Quiet hours end time', null=True),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='quiet_hours',
            field=models.BooleanField(default=False, help_text='Enable quiet hours for notifications'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='quiet_start',
            field=models.TimeField(blank=True, help_text='Quiet hours start time', null=True),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='sms_notifications',
            field=models.BooleanField(default=False, help_text='Receive notifications via SMS'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='system_updates',
            field=models.BooleanField(default=True, help_text='Product updates and system changes'),
        ),
    ]
