# Generated by Django 5.2.5 on 2025-08-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_stats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='booking_count',
            new_name='bookings_count',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='client_count',
            new_name='clients_count',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='gallery_count',
            new_name='galleries_count',
        ),
        migrations.AddField(
            model_name='stats',
            name='photos_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
