# Generated by Django 5.2.5 on 2025-08-24 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_rename_booking_count_stats_bookings_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='sparks_per_day',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='last_reset',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='sparks_remaining',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
