# Generated by Django 5.2.5 on 2025-08-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscriptionplan_sparks_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='sparks_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
