# Generated by Django 5.2.5 on 2025-08-14 12:47

import django.db.models.deletion
import studio.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(help_text='Used for subdomain: <slug>.<BASE_DOMAIN>', unique=True)),
                ('custom_domain', models.CharField(blank=True, help_text='Exact host only (no http/https). Example: johndoe.com', max_length=255, null=True, unique=True)),
                ('custom_domain_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(default=studio.models._default_token, editable=False, help_text='TXT record token for domain ownership checks', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
    ]
