# Generated by Django 5.2.5 on 2025-08-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studio',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='studio_covers/'),
        ),
        migrations.AddField(
            model_name='studio',
            name='font_choice',
            field=models.CharField(default='Sans-serif', max_length=50),
        ),
        migrations.AddField(
            model_name='studio',
            name='primary_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='studio',
            name='secondary_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
