# Generated by Django 5.2.5 on 2025-08-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_studio_bio_studio_cover_photo_studio_font_choice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studio',
            old_name='font_choice',
            new_name='font',
        ),
        migrations.AddField(
            model_name='studio',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='studio_favicons/'),
        ),
        migrations.AddField(
            model_name='studio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='studio_logos/'),
        ),
    ]
