# Generated by Django 5.2.5 on 2025-08-15 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_rename_font_choice_studio_font_studio_favicon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='favicon',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='logo',
        ),
    ]
