# Generated by Django 5.2.5 on 2025-08-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_remove_studio_favicon_remove_studio_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studio',
            old_name='bio',
            new_name='tagline',
        ),
        migrations.AddField(
            model_name='studio',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
