# Generated by Django 5.2.5 on 2025-08-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_rename_bio_studio_tagline_studio_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='theme',
            field=models.CharField(choices=[('modern', 'Modern'), ('minimalist', 'Minimalist'), ('magazine', 'Magazine')], default='modern', max_length=50),
        ),
    ]
