# Generated by Django 5.2.5 on 2025-08-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_studio_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='theme',
            field=models.CharField(choices=[('retro', 'Retro'), ('minimalist', 'Minimalist'), ('magazine', 'Magazine')], default='modern', max_length=50),
        ),
    ]
