# Generated by Django 5.2.5 on 2025-08-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_alter_studio_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='theme',
            field=models.CharField(choices=[('retro', 'Retro'), ('minimalist', 'Minimalist'), ('magazine', 'Magazine')], default='minimalist', max_length=50),
        ),
    ]
